# Generated by Django 5.0.2 on 2024-03-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('tempat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('nomor', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('angkatan', models.IntegerField()),
                ('jurusan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PengurusInti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BPH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.divisi')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jurusan', models.CharField(max_length=255)),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.kelompok')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.mentor')),
            ],
        ),
        migrations.AddField(
            model_name='kelompok',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.mentor'),
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presensi', models.TextField()),
                ('materi', models.CharField(max_length=255)),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.kelompok')),
            ],
        ),
        migrations.CreateModel(
            name='Pembicara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('acara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acara')),
            ],
        ),
        migrations.CreateModel(
            name='Rapat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kehadiran', models.TextField()),
                ('waktu', models.DateField()),
                ('tempat', models.CharField(max_length=255)),
                ('kesimpulan', models.TextField()),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.divisi')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tipe', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('benefit', models.TextField()),
                ('acara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.acara')),
            ],
        ),
    ]
