# Generated by Django 5.0.2 on 2024-03-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bph',
            old_name='bidang',
            new_name='divisi',
        ),
    ]
