# Generated by Django 5.0.2 on 2024-03-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_kelompok_mentor_mentor_kelompok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='harga',
        ),
    ]
